In [35]:
import tensorflow as tf
import numpy as np
import pandas as pd
from clean_data import load_clean_data as lcd
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [12]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
b = np.arange(20, 30)
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
sess = tf.Session()

In [15]:
x = tf.constant(a)
y = tf.constant(b)
xy = tf.mul(x, y)

In [16]:
sess.run(xy)

array([[   0,   21,   44,   69,   96,  125,  156,  189,  224,  261],
       [ 200,  231,  264,  299,  336,  375,  416,  459,  504,  551],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 600,  651,  704,  759,  816,  875,  936,  999, 1064, 1131],
       [ 800,  861,  924,  989, 1056, 1125, 1196, 1269, 1344, 1421],
       [1000, 1071, 1144, 1219, 1296, 1375, 1456, 1539, 1624, 1711],
       [1200, 1281, 1364, 1449, 1536, 1625, 1716, 1809, 1904, 2001],
       [1400, 1491, 1584, 1679, 1776, 1875, 1976, 2079, 2184, 2291],
       [1600, 1701, 1804, 1909, 2016, 2125, 2236, 2349, 2464, 2581],
       [1800, 1911, 2024, 2139, 2256, 2375, 2496, 2619, 2744, 2871]])

In [18]:
churn = pd.read_csv('churn.csv')

In [19]:
churn.head()

avg_dist  avg_rating_by_driver  avg_rating_of_driver  avg_surge  \
0      3.67                   5.0                   4.7       1.10   
1      8.26                   5.0                   5.0       1.00   
2      0.77                   5.0                   4.3       1.00   
3      2.36                   4.9                   4.6       1.14   
4      3.13                   4.9                   4.4       1.19   

             city last_trip_date    phone signup_date  surge_pct  \
0  King's Landing     2014-06-17   iPhone  2014-01-25       15.4   
1         Astapor     2014-05-05  Android  2014-01-29        0.0   
2         Astapor     2014-01-07   iPhone  2014-01-06        0.0   
3  King's Landing     2014-06-29   iPhone  2014-01-10       20.0   
4      Winterfell     2014-03-15  Android  2014-01-27       11.8   

   trips_in_first_30_days luxury_car_user  weekday_pct  
0                       4            True         46.2  
1                       0           False         50.0  
2                       3           False        100.0  
3                       9            True         80.0  
4                      14           False         82.4

In [21]:
df, X, y = lcd()

In [22]:
X.shape

(50000, 13)

In [23]:
y.shape

(50000,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [27]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
model.coef_

array([[  3.32820408e-02,   1.57197882e-01,   1.35770184e-01,
          2.24401251e-01,  -4.80727403e-03,  -9.55086610e-02,
         -8.34610987e-01,  -1.36584803e-04,  -3.71074749e-02,
          5.48977928e-03,  -1.03534154e+00,  -1.62733126e+00,
         -4.73287434e-01]])

In [29]:
model.intercept_

array([ 0.61260535])

In [88]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.67      0.47      0.55      4564
          1       0.74      0.87      0.80      7936

avg / total       0.71      0.72      0.71     12500



In [89]:
logistic_regression_acc = accuracy_score(y_test, y_pred)
print(logistic_regression_acc)

0.72184


In [55]:
model.coef_.reshape(-1, 1).shape

(13, 1)

In [74]:
coefs = tf.constant(model.coef_.reshape(-1, 1), dtype=tf.float32) # important! dtype must match x (what it's multiplied by)
intercept = tf.constant(model.intercept_, dtype=tf.float32)

In [75]:
x = tf.placeholder(tf.float32, [None, 13]) # 13 features in input data
y = tf.placeholder(tf.float32, [None, 1]) # either a churn (1) or not (0)

In [76]:
pred = tf.nn.sigmoid(tf.matmul(x, coefs) + intercept) # sigmoid makes it logistic

In [77]:
sess = tf.Session()

In [78]:
init = tf.initialize_all_variables()
sess.run(init)

In [90]:
y_pred = sess.run(pred, feed_dict={x: X_test})

In [91]:
y_pred.sum()

7939.373

In [92]:
y_pred.shape

(12500, 1)

In [93]:
y_pred_round = np.round(y_pred)

In [94]:
y_pred_round.sum()

9283.0

In [96]:
neural_net_acc = accuracy_score(y_test, y_pred_round)
print(neural_net_acc)
print(logistic_regression_acc)

0.72184
0.72184


Nice! Now let's define a cost function and fit it, to make sure the weights don't change.

Nice! Now let's make a NN with one hidden layer.

In [97]:
coefs = tf.constant(model.coef_.reshape(-1, 1), dtype=tf.float32) # important! dtype must match x (what it's multiplied by)
intercept = tf.constant(model.intercept_, dtype=tf.float32)

In [ ]:
x = tf.placeholder(tf.float32, [None, 13]) # 13 features in input data
y = tf.placeholder(tf.float32, [None, 1]) # either a churn (1) or not (0)

In [ ]:
hidden_1 = tf.Variable(tf.random_normal([n_input, n_hidden_1])